### ISSUE TITLE
Add simulator for AB test tron: March 31st

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/demo-nodetron#41]
For the purposes of the programmability course, we'd like to see a simulator for the docker-based deployment of the AB test demo app (DEMO-2536-ab-test-app).

## Summary

The demotron-based deployment of the demo infrastructure in branch DEMO-2536-ab-test-app contains a simulator for generating traffic to the demo app. If possible, we'd like to see this in the docker-based deployment as well, since that's the method of choice for the programmability course as it has fewer prerequisites.

## Desired Behavior

Generate traffic at irregular intervals by making API requests to the `/subscribe` and `/` endpoints. The traffic should alternate between version A and B in an indeterministic way with a higher percentage subscribing via version B. 

The reason for both endpoints is to generate some NR `page_view` events and some `subscription` events. It would be nice for there to be more page views than subscriptions, but this isn't mandatory.

**Comment by aswanson-nr** [comment]
These changes will also allow us to increase the RPM of the scenario, it is currently limited to prevent the micro EC2 instance from running out of memory.
The majority of work here will be updating the [simulator](https://github.com/newrelic/demo-simulator) application to run within a container. We will also need to think about how the scenario files are moved around and stored, since they would no longer be stored in the deployment configuration.

**Comment by jpvajda** [comment]
Checking if this should be in Sprint 1 as @alexronquillo was asking about it.

**Comment by aswanson-nr** [comment]
I see this issue having 3 parts:
1. Containerize the newrelic/demo-simulator.
	* Allow scenario json files to be mounted into the container.
	* The container must be able to run chrome, since the simulator uses the selenium chrome webdriver. https://github.com/SeleniumHQ/docker-selenium seems like a starting point for the image.
	* Create a pipeline to publish the image on merges to main.
2. Create a docker-compose file to deploy the simulator and A/B test application.
	* This should mount in the scenario files for the simulator.
3. Fine tune the scenarios once it's all working together.

**Comment by aswanson-nr** [comment]
PR for the simulator changes newrelic/demo-simulator/pull/14

**Comment by aswanson-nr** [comment]
Final PR into the course https://github.com/newrelic-experimental/nru-programmability-course/pull/6
